spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usedmarket?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: nswon0729@

  security:
    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      token-validity-in-seconds: 86400

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379

#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB

file:
  dir : /Users/a1/Desktop/images/

fcm:
  certification: push-alarm-24ef8-firebase-adminsdk-8wjmt-41627cf753.json

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

cloud:
  aws:
    credentials:
      access-key: AKIASAX4HQX6RMT26Y6M
      secret-key: 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

    region:
      static: ap-northeast-2
    s3:
      bucket: usedmarket
    stack:
      auto: false

